pipeline {
    agent any
    stages {
        stage('Cleanup') {
            steps {
                script {
                    deleteDir()
                }
            }
        }
        stage('Git Clone') {
            steps {
                bat 'git clone https://github.com/Krishraj111/react-e-commerce.git .'
            }
        }
        stage('Clear previous Builds') {
            steps {
                bat 'docker compose down'
            }
        }
        stage('Docker Compose') {
            steps {
                bat 'docker compose up -d --build'
            }
        }
        stage('Testing') {
            steps {
                script {
                    bat '''
                    echo Waiting for server to start...
                    for /L %%i in (1,1,10) do (
                        curl http://localhost:3000 && exit /b 0
                        timeout /t 5 >nul
                        echo Retry %%i...
                    )
                    echo Server did not respond in time.
                    exit /b 1
                    '''
                }
            }
        }
    }
}
